fix: repo upgrade
Neovici/cosmoz-data-nav pull request #116
Opened 2020-04-11 09:44 UTC by nomego

- drop unused files
  - analysis.json
  - index.html
  - polymer.json
  - wct.conf.json
- switch to karm
  - add karma problem matcher
- switch github workflow to setup-node eslint problem matcher
- update codeclimate conf
- update vscode settings
- add es-dev-server
- upgrade deps
- convert most tests to karma

2020-04-11 22:31 UTC, nomego commented
Should also mention here, this updates the behavior to fire 'need-data' for all preloading items at once instead of waiting for details sequentially.
It makes better use of the FE data service and doesn't seem to cause issues with the old approach either.

2020-04-14 07:03 UTC, Wurper approved these changes

2020-04-14 07:03 UTC, Wurper commented on cosmoz-data-nav.js
>  		// index 0 is incomplete element
Is this comment still true/relevant?

2020-04-14 07:22 UTC, cristinecula requested changes
Data-nav is already doing waaay too much as it is, so I'm very reluctant to complicate it's behavior even more with the parallel-data-requests flag. Is it really an issue that data-nav requests the same item multiple times? Shouldn't it be the responsibility of the layer above data-nav that deduplicates the requests?

2020-04-14 07:22 UTC, cristinecula commented on test/helpers/utils.js
> +				}
What is this used for?

2020-04-14 07:22 UTC, cristinecula commented on test/bugs.test.js
> +		}
Asserting an assert error message is very smelly and very hard to understand it's purpose. Try expressing the assertion differently.

Also, tests do not need to be so DRY. I would refactor `oneRequestPerItem` to a beforeTest hook. You can create a different suite so you don't affect the other test.

2020-04-14 08:28 UTC, cristinecula approved these changes
As discussed on Slack, this change is actually making data-nav less opinionated. :+1:

2020-04-15 05:50 UTC, Wurper approved these changes

2020-04-15 06:52 UTC, cristinecula approved these changes

2020-04-15 06:54 UTC, merged